sudo: required

services:
  - docker

before_script:
  - docker build -t guitmz/bucket .
 
script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push guitmz/bucket
